version: "3.7"
services:
    api:
        image: shopping:latest
        environment:
            - ConnectionStrings__shopping=server=sql;database=shopping;user id=SA;password=Tokyo_Joe_138!!
        networks:
            - my-network
        ports:
            - 8080:80
    sql:
        image: mcr.microsoft.com/mssql/server
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Tokyo_Joe_138!!
            - MSSQL_PID=developer
        ports: 
            - 1433:1433
        networks:
            - my-network
networks:
    my-network:
        driver: bridge